global:
  ingress:
    ingressClassName: kong
    controllerUrl: https://api.llmo.cloudnatix.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/response-buffering: "false"
    tls:
      hosts:
      - api.llmo.cloudnatix.com
      secretName: api-tls

  database:
    host: llmo-demo-control-plane.cteocyc42bh3.us-east-2.rds.amazonaws.com
    port: 5432
    username: ps_user
    ssl:
      mode: require

  databaseSecret:
    name: postgres-rds
    key: password

  objectStore:
    s3:
      # TODO(kenji): Use HTTPS instead of HTTP.
      endpointUrl: http://minio.minio:9000
      region: dummy
      bucket: llm-operator

  awsSecret:
    name: aws
    accessKeyIdKey: accessKeyId
    secretAccessKeyKey: secretAccessKey

  workerServiceIngress:
    create: true
    annotations:
      konghq.com/protocols: grpc,grpcs
      cert-manager.io/cluster-issuer: letsencrypt

  workerServiceGrpcService:
    annotations:
      konghq.com/protocol: grpc


dex-server:
  oauth2:
    passwordConnector:
      enable: false
    responseTypes:
    - code
  connectors:
  - type: oidc
    id: okta
    name: okta
    config:
      # Using the "Internal" Okta API authorization server
      issuer: https://login.cloudnatix.com/oauth2/aus24366mbRFxF3De4x7
      clientID: 0oak1yta82395U5wP4x7
      clientSecret: nxU6XRatwKdweHn-CgS5YiYKNfahfS8l1N3kjhqNeWfPEAEb7ub2TfvezU5OYifH
      redirectURI: https://api.llmo.cloudnatix.com/v1/dex/callback
      insecureSkipEmailVerified: true
      scopes:
      - profile
      - email
      - offline_access

  enablePasswordDb: false
  staticPassword:
    enable: false
  expiry:
   idTokens: 1h
   refreshTokens:
     validIfNotUsedFor: 168h


inference-manager-server:
  workerServiceTls:
    enable: true
    secretName: llmo-cert
  workerServiceGrpcService:
    type: NodePort
    nodePort: 31235
  service:
    annotations:
      konghq.com/connect-timeout: "360000"
      konghq.com/read-timeout: "360000"
      konghq.com/write-timeout: "360000"


session-manager-server:
  workerServiceTls:
    enable: true
    secretName: llmo-cert
  workerServiceHttpService:
    type: NodePort
    nodePort: 31234


vector-store-manager-server:
  llmEngineAddr: ollama.ollama:8080
